import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'

import Head from 'next/head'
import { MantineProvider, ColorSchemeScript, AppShell, Code, Button, Center } from '@mantine/core'
import { Amplify } from 'aws-amplify'
import { theme } from '@/constants'
import awsConfig from '@/aws-exports'
import { Notifications } from '@mantine/notifications'
import { ModalsProvider } from '@mantine/modals'

Amplify.configure(awsConfig)

export default function App({ Component, pageProps }: any) {
  return (
    <>
      <ColorSchemeScript defaultColorScheme='dark' />
      <MantineProvider theme={theme} defaultColorScheme='dark'>
        <Head>
          <title>Table Code System</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Notifications position='top-right' />
        <AppShell
          padding='md'
          header={{
            height: 60,
          }}
        >
          <AppShell.Header>
            <Center h='100%'>
              <Code>Data Table System v.1.0.0</Code>
            </Center>
          </AppShell.Header>
          <AppShell.Main>
            <Component {...pageProps} />
          </AppShell.Main>
        </AppShell>
      </MantineProvider>
    </>
  )
}
