import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Button, Center } from '@mantine/core'

import { useQuery } from '@/utils'
import { CodeItem } from '@/models'
import { GetCodeItemQueryVariables } from '@/graphql/types'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { loading, error, request } = useQuery<CodeItem, GetCodeItemQueryVariables>({
    query: 'getCodeItem',
    variables: { itemCode: '123' },
    settings: {
      next(item) {
        item.itemCode
      },
    },
  })

  const callMe = () => {
    request().then((res) => {
      res.data?.itemCode
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Center w='100vw' h='100vh'>
        <Button loading={loading} size='xl' onClick={request}>
          Click me!
        </Button>
      </Center>
    </>
  )
}
